// =============================================================================
// MOCK DATA FOR DEMO MODE
// Realistic training content based on EHS quarterly structure
// =============================================================================

import type { Unterweisungsverweis, QuarterId } from '@/src/types/training'

/**
 * Generate a unique ID
 */
function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
}

/**
 * Mock training content references
 * Follows Q1-Q4 quarterly structure with realistic EHS modules
 */
export const mockVerweise: Unterweisungsverweis[] = [
  // ==========================================================================
  // Q1 – Sicher starten
  // ==========================================================================
  
  // M1: Werkregeln & Sicherheitscharta
  {
    id: generateId(),
    Title: 'Werkregeln & Sicherheitscharta - Präsentation',
    QuarterId: 'Q1',
    QuarterTitle: 'Q1 – Sicher starten',
    ModuleId: 'Q1-M1',
    ModuleTitle: 'Werkregeln & Sicherheitscharta',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Werkregeln 2024',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q1/M1/werkregeln-praesentation.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q1/M1',
    FileName: 'werkregeln-praesentation.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Sicherheitscharta Video',
    QuarterId: 'Q1',
    QuarterTitle: 'Q1 – Sicher starten',
    ModuleId: 'Q1-M1',
    ModuleTitle: 'Werkregeln & Sicherheitscharta',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Unsere Sicherheitscharta',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q1/M1/sicherheitscharta-video.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q1/M1',
    FileName: 'sicherheitscharta-video.mp4',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Werkregeln Referenz',
    QuarterId: 'Q1',
    QuarterTitle: 'Q1 – Sicher starten',
    ModuleId: 'Q1-M1',
    ModuleTitle: 'Werkregeln & Sicherheitscharta',
    DocType: 'Document',
    DocCategory: 'Referenz',
    LinkLabel: 'Dokument: Werkregeln (PDF)',
    ShowInTraining: true,
    SortOrder: 3,
    ServerRelativeUrl: '/sites/ehs/content/Q1/M1/werkregeln.pdf',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q1/M1',
    FileName: 'werkregeln.pdf',
    OpenMode: 'download',
  },
  
  // M2: Risikomanagement & Ereignisfall
  {
    id: generateId(),
    Title: 'Risikomanagement Präsentation',
    QuarterId: 'Q1',
    QuarterTitle: 'Q1 – Sicher starten',
    ModuleId: 'Q1-M2',
    ModuleTitle: 'Risikomanagement & Ereignisfall',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Risikomanagement',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q1/M2/risikomanagement.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q1/M2',
    FileName: 'risikomanagement.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Ereignisfall Meldung',
    QuarterId: 'Q1',
    QuarterTitle: 'Q1 – Sicher starten',
    ModuleId: 'Q1-M2',
    ModuleTitle: 'Risikomanagement & Ereignisfall',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Ereignisfall richtig melden',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q1/M2/ereignisfall-meldung.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q1/M2',
    FileName: 'ereignisfall-meldung.mp4',
    OpenMode: 'newTab',
  },
  
  // M3: Brandschutz & Evakuierung
  {
    id: generateId(),
    Title: 'Brandschutz Präsentation',
    QuarterId: 'Q1',
    QuarterTitle: 'Q1 – Sicher starten',
    ModuleId: 'Q1-M3',
    ModuleTitle: 'Brandschutz & Evakuierung',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Brandschutz',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q1/M3/brandschutz.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q1/M3',
    FileName: 'brandschutz.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Evakuierungsplan Video',
    QuarterId: 'Q1',
    QuarterTitle: 'Q1 – Sicher starten',
    ModuleId: 'Q1-M3',
    ModuleTitle: 'Brandschutz & Evakuierung',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Evakuierung',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q1/M3/evakuierung.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q1/M3',
    FileName: 'evakuierung.mp4',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Flucht- und Rettungswege',
    QuarterId: 'Q1',
    QuarterTitle: 'Q1 – Sicher starten',
    ModuleId: 'Q1-M3',
    ModuleTitle: 'Brandschutz & Evakuierung',
    DocType: 'Document',
    DocCategory: 'Referenz',
    LinkLabel: 'Plan: Flucht- und Rettungswege',
    ShowInTraining: true,
    SortOrder: 3,
    ServerRelativeUrl: '/sites/ehs/content/Q1/M3/fluchtplan.pdf',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q1/M3',
    FileName: 'fluchtplan.pdf',
    OpenMode: 'download',
  },
  
  // ==========================================================================
  // Q2 – Sicher arbeiten
  // ==========================================================================
  
  // M1: Arbeiten in der Höhe / Leitern & Tritte
  {
    id: generateId(),
    Title: 'Arbeiten in der Höhe',
    QuarterId: 'Q2',
    QuarterTitle: 'Q2 – Sicher arbeiten',
    ModuleId: 'Q2-M1',
    ModuleTitle: 'Arbeiten in der Höhe / Leitern & Tritte',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Höhenarbeit sicher gestalten',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q2/M1/hoehenarbeit.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q2/M1',
    FileName: 'hoehenarbeit.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Leitern & Tritte Video',
    QuarterId: 'Q2',
    QuarterTitle: 'Q2 – Sicher arbeiten',
    ModuleId: 'Q2-M1',
    ModuleTitle: 'Arbeiten in der Höhe / Leitern & Tritte',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Sichere Nutzung von Leitern',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q2/M1/leitern-video.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q2/M1',
    FileName: 'leitern-video.mp4',
    OpenMode: 'newTab',
  },
  
  // M2: Hebevorgänge / Krane / Lasten
  {
    id: generateId(),
    Title: 'Hebevorgänge Präsentation',
    QuarterId: 'Q2',
    QuarterTitle: 'Q2 – Sicher arbeiten',
    ModuleId: 'Q2-M2',
    ModuleTitle: 'Hebevorgänge / Krane / Lasten',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Sicheres Heben und Transportieren',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q2/M2/hebevorgaenge.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q2/M2',
    FileName: 'hebevorgaenge.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Kranbetrieb Video',
    QuarterId: 'Q2',
    QuarterTitle: 'Q2 – Sicher arbeiten',
    ModuleId: 'Q2-M2',
    ModuleTitle: 'Hebevorgänge / Krane / Lasten',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Kranbetrieb sicher durchführen',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q2/M2/kranbetrieb.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q2/M2',
    FileName: 'kranbetrieb.mp4',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Lastenhandhabung Checkliste',
    QuarterId: 'Q2',
    QuarterTitle: 'Q2 – Sicher arbeiten',
    ModuleId: 'Q2-M2',
    ModuleTitle: 'Hebevorgänge / Krane / Lasten',
    DocType: 'Document',
    DocCategory: 'Referenz',
    LinkLabel: 'Checkliste: Lastenhandhabung',
    ShowInTraining: true,
    SortOrder: 3,
    ServerRelativeUrl: '/sites/ehs/content/Q2/M2/lastenhandhabung-checkliste.pdf',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q2/M2',
    FileName: 'lastenhandhabung-checkliste.pdf',
    OpenMode: 'download',
  },
  
  // M3: Fahrzeugbewegung / Transporte / Schienenverkehr
  {
    id: generateId(),
    Title: 'Fahrzeugbewegung Präsentation',
    QuarterId: 'Q2',
    QuarterTitle: 'Q2 – Sicher arbeiten',
    ModuleId: 'Q2-M3',
    ModuleTitle: 'Fahrzeugbewegung / Transporte / Schienenverkehr',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Sicherer Fahrzeugverkehr',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q2/M3/fahrzeugverkehr.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q2/M3',
    FileName: 'fahrzeugverkehr.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Schienenverkehr Video',
    QuarterId: 'Q2',
    QuarterTitle: 'Q2 – Sicher arbeiten',
    ModuleId: 'Q2-M3',
    ModuleTitle: 'Fahrzeugbewegung / Transporte / Schienenverkehr',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Schienenverkehr im Werk',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q2/M3/schienenverkehr.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q2/M3',
    FileName: 'schienenverkehr.mp4',
    OpenMode: 'newTab',
  },
  
  // ==========================================================================
  // Q3 – Sicher handeln
  // ==========================================================================
  
  // M1: Gefahrstoffe
  {
    id: generateId(),
    Title: 'Gefahrstoffe Präsentation',
    QuarterId: 'Q3',
    QuarterTitle: 'Q3 – Sicher handeln',
    ModuleId: 'Q3-M1',
    ModuleTitle: 'Gefahrstoffe',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Umgang mit Gefahrstoffen',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q3/M1/gefahrstoffe.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q3/M1',
    FileName: 'gefahrstoffe.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Gefahrstoffe Kennzeichnung Video',
    QuarterId: 'Q3',
    QuarterTitle: 'Q3 – Sicher handeln',
    ModuleId: 'Q3-M1',
    ModuleTitle: 'Gefahrstoffe',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: GHS-Kennzeichnung verstehen',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q3/M1/ghs-kennzeichnung.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q3/M1',
    FileName: 'ghs-kennzeichnung.mp4',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Sicherheitsdatenblätter',
    QuarterId: 'Q3',
    QuarterTitle: 'Q3 – Sicher handeln',
    ModuleId: 'Q3-M1',
    ModuleTitle: 'Gefahrstoffe',
    DocType: 'Reference',
    DocCategory: 'Referenz',
    LinkLabel: 'Link: Sicherheitsdatenblätter',
    ShowInTraining: true,
    SortOrder: 3,
    ServerRelativeUrl: 'https://example.com/sdb',
    LibraryName: 'External',
    FolderPath: '',
    FileName: '',
    OpenMode: 'newTab',
  },
  
  // M2: PSA / Handschutz / Arbeitsschutzmittel
  {
    id: generateId(),
    Title: 'PSA Präsentation',
    QuarterId: 'Q3',
    QuarterTitle: 'Q3 – Sicher handeln',
    ModuleId: 'Q3-M2',
    ModuleTitle: 'PSA / Handschutz / Arbeitsschutzmittel',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Persönliche Schutzausrüstung',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q3/M2/psa.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q3/M2',
    FileName: 'psa.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Handschutz Video',
    QuarterId: 'Q3',
    QuarterTitle: 'Q3 – Sicher handeln',
    ModuleId: 'Q3-M2',
    ModuleTitle: 'PSA / Handschutz / Arbeitsschutzmittel',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Richtiger Handschutz',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q3/M2/handschutz.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q3/M2',
    FileName: 'handschutz.mp4',
    OpenMode: 'newTab',
  },
  
  // M3: Elektrische Sicherheit / LOTO / Maschinensicherheit
  {
    id: generateId(),
    Title: 'Elektrische Sicherheit Präsentation',
    QuarterId: 'Q3',
    QuarterTitle: 'Q3 – Sicher handeln',
    ModuleId: 'Q3-M3',
    ModuleTitle: 'Elektrische Sicherheit / LOTO / Maschinensicherheit',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Elektrische Sicherheit',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q3/M3/elektro-sicherheit.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q3/M3',
    FileName: 'elektro-sicherheit.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'LOTO Video',
    QuarterId: 'Q3',
    QuarterTitle: 'Q3 – Sicher handeln',
    ModuleId: 'Q3-M3',
    ModuleTitle: 'Elektrische Sicherheit / LOTO / Maschinensicherheit',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Lockout/Tagout richtig anwenden',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q3/M3/loto.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q3/M3',
    FileName: 'loto.mp4',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Maschinensicherheit Handbuch',
    QuarterId: 'Q3',
    QuarterTitle: 'Q3 – Sicher handeln',
    ModuleId: 'Q3-M3',
    ModuleTitle: 'Elektrische Sicherheit / LOTO / Maschinensicherheit',
    DocType: 'Document',
    DocCategory: 'Referenz',
    LinkLabel: 'Handbuch: Maschinensicherheit',
    ShowInTraining: true,
    SortOrder: 3,
    ServerRelativeUrl: '/sites/ehs/content/Q3/M3/maschinensicherheit.pdf',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q3/M3',
    FileName: 'maschinensicherheit.pdf',
    OpenMode: 'download',
  },
  
  // ==========================================================================
  // Q4 – Sicher abschließen
  // ==========================================================================
  
  // M1: Umwelt / Energie / Biodiversität
  {
    id: generateId(),
    Title: 'Umweltmanagement Präsentation',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M1',
    ModuleTitle: 'Umwelt / Energie / Biodiversität',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Umweltmanagement im Betrieb',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M1/umweltmanagement.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M1',
    FileName: 'umweltmanagement.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Energieeffizienz Video',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M1',
    ModuleTitle: 'Umwelt / Energie / Biodiversität',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Energie sparen im Arbeitsalltag',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M1/energieeffizienz.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M1',
    FileName: 'energieeffizienz.mp4',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Biodiversität am Standort',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M1',
    ModuleTitle: 'Umwelt / Energie / Biodiversität',
    DocType: 'Document',
    DocCategory: 'Referenz',
    LinkLabel: 'Broschüre: Biodiversität am Standort',
    ShowInTraining: true,
    SortOrder: 3,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M1/biodiversitaet.pdf',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M1',
    FileName: 'biodiversitaet.pdf',
    OpenMode: 'download',
  },
  
  // M2: EHS-System / Zertifizierungen / Contractor Control
  {
    id: generateId(),
    Title: 'EHS-System Präsentation',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M2',
    ModuleTitle: 'EHS-System / Zertifizierungen / Contractor Control',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: Unser EHS-Managementsystem',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M2/ehs-system.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M2',
    FileName: 'ehs-system.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Contractor Control Video',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M2',
    ModuleTitle: 'EHS-System / Zertifizierungen / Contractor Control',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Fremdfirmenmanagement',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M2/contractor-control.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M2',
    FileName: 'contractor-control.mp4',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Zertifizierungen Übersicht',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M2',
    ModuleTitle: 'EHS-System / Zertifizierungen / Contractor Control',
    DocType: 'Document',
    DocCategory: 'Referenz',
    LinkLabel: 'Übersicht: ISO 14001 & ISO 45001',
    ShowInTraining: true,
    SortOrder: 3,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M2/zertifizierungen.pdf',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M2',
    FileName: 'zertifizierungen.pdf',
    OpenMode: 'download',
  },
  
  // M3: Sonderthemen / Methoden / Bereichsprozesse
  {
    id: generateId(),
    Title: 'Sonderthemen Präsentation',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M3',
    ModuleTitle: 'Sonderthemen / Methoden / Bereichsprozesse',
    DocType: 'Presentation',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Präsentation: EHS-Sonderthemen',
    ShowInTraining: true,
    SortOrder: 1,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M3/sonderthemen.pptx',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M3',
    FileName: 'sonderthemen.pptx',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'Bereichsprozesse Video',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M3',
    ModuleTitle: 'Sonderthemen / Methoden / Bereichsprozesse',
    DocType: 'Video',
    DocCategory: 'Unterweisung',
    LinkLabel: 'Video: Bereichsspezifische Prozesse',
    ShowInTraining: true,
    SortOrder: 2,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M3/bereichsprozesse.mp4',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M3',
    FileName: 'bereichsprozesse.mp4',
    OpenMode: 'newTab',
  },
  {
    id: generateId(),
    Title: 'EHS-Methoden Toolkit',
    QuarterId: 'Q4',
    QuarterTitle: 'Q4 – Sicher abschließen',
    ModuleId: 'Q4-M3',
    ModuleTitle: 'Sonderthemen / Methoden / Bereichsprozesse',
    DocType: 'Document',
    DocCategory: 'Referenz',
    LinkLabel: 'Toolkit: EHS-Analysemethoden',
    ShowInTraining: true,
    SortOrder: 3,
    ServerRelativeUrl: '/sites/ehs/content/Q4/M3/ehs-toolkit.pdf',
    LibraryName: 'EHS-Content',
    FolderPath: 'Q4/M3',
    FileName: 'ehs-toolkit.pdf',
    OpenMode: 'download',
  },
]

/**
 * Get modules deduplicated by ModuleId
 */
export function getAggregatedModules() {
  const moduleMap = new Map<string, {
    ModuleId: string
    ModuleTitle: string
    QuarterId: QuarterId
    QuarterTitle: string
    SortOrder: number
    ContentCount: number
  }>()
  
  for (const verweis of mockVerweise) {
    if (!moduleMap.has(verweis.ModuleId)) {
      moduleMap.set(verweis.ModuleId, {
        ModuleId: verweis.ModuleId,
        ModuleTitle: verweis.ModuleTitle,
        QuarterId: verweis.QuarterId,
        QuarterTitle: verweis.QuarterTitle,
        SortOrder: verweis.SortOrder,
        ContentCount: 1,
      })
    } else {
      const existing = moduleMap.get(verweis.ModuleId)!
      existing.ContentCount++
    }
  }
  
  return Array.from(moduleMap.values()).sort((a, b) => {
    // Sort by quarter first, then by module within quarter
    if (a.QuarterId !== b.QuarterId) {
      return a.QuarterId.localeCompare(b.QuarterId)
    }
    return a.ModuleId.localeCompare(b.ModuleId)
  })
}
